export const JobLists = [
  {
    category: "Engineering Job",
    jobs: [
      {
        id: "1",
        category: "EngineeringJobs",
        logo: "/company-1.png",
        title: "Senior Manager, Analytics Engineering",
        path: "",
        company: "Intercom",
        location: "California",
        salary: "$214k -  $290k",
        datePosted: "2023-10-23",
      },
      {
        id: "2",
        category: "EngineeringJobs",
        logo: "/company-2.png",
        title: "Senior Software Engineer",
        path: "",
        company: "InnovateTech",
        location: "San Francisco",
        salary: "$200k -  $260k",
        datePosted: "2023-12-08",
      },
      {
        id: "3",
        category: "EngineeringJobs",
        logo: "/company-3.png",
        title: "DevOps Engineer",
        path: "",
        company: "CloudBuilders",
        location: "Seattle",
        salary: "$190k -  $250k",
        datePosted: "2023-12-17",
      },
      {
        id: "4",
        category: "EngineeringJobs",
        logo: "/company-4.png",
        title: "Product Manager",
        path: "",
        company: "Digital Solutions Inc.",
        location: "Seattle",
        salary: "$200k -  $280k",
        datePosted: "2023-11-30",
      },
      {
        id: "5",
        category: "EngineeringJobs",
        logo: "/company-5.png",
        title: "Software Engineer (Frontend)",
        path: "",
        company: "CodeCrafters",
        location: "Austin",
        salary: "$170k -  $220k",
        datePosted: "2023-12-01",
      },
      {
        id: "6",
        category: "EngineeringJobs",
        logo: "/company-6.png",
        title: "UX/UI Designer",
        path: "",
        company: "DesignHub",
        location: "Los Angeles",
        salary: "$160k -  $210k",
        datePosted: "2023-12-02",
      },
    ],
  },
  {
    category: "Product Job",
    jobs: [
      {
        id: "1",
        category: "ProductJobs",
        logo: "/company-1.png",
        title: "Strategic Account Executive",
        path: "",
        company: "Mixpanel",
        location: "San Francisco",
        salary: "$216k -  $354k",
        datePosted: "2023-11-23",
      },
      {
        id: "2",
        category: "ProductJobs",
        logo: "/company-2.png",
        title: "Product Manager",
        path: "",
        company: "ProductVisionaries",
        location: "Seattle",
        salary: "$190k -  $250k",
        datePosted: "2023-12-09",
      },
      {
        id: "3",
        category: "ProductJobs",
        logo: "/company-3.png",
        title: "Technical Product Manager",
        path: "",
        company: "TechInnovate",
        location: "San Francisco",
        salary: "$200k -  $260k",
        datePosted: "2023-12-22",
      },
      {
        id: "4",
        category: "ProductJobs",
        logo: "/company-4.png",
        title: "Product Designer",
        path: "",
        company: "DesignCraft",
        location: "New York",
        salary: "$180k -  $230k",
        datePosted: "2023-12-23",
      },
      {
        id: "5",
        category: "ProductJobs",
        logo: "/company-5.png",
        title: "Product Marketing Manager",
        path: "",
        company: "MarketMasters",
        location: "Austin",
        salary: "$210k -  $270k",
        datePosted: "2023-12-24",
      },
      {
        id: "6",
        category: "ProductJobs",
        logo: "/company-6.png",
        title: "Product Operations Specialist",
        path: "",
        company: "OperateSmart",
        location: "Denver",
        salary: "$220k -  $280k",
        datePosted: "2023-12-25",
      },
    ],
  },
  {
    category: "Design Job",

    jobs: [
      {
        id: "1",
        category: "DesignJobs",
        logo: "/company-1.png",
        title: "UI/UX Designer",
        path: "",
        company: "CreativeCraft",
        location: "New York",
        salary: "$180k -  $230k",
        datePosted: "2023-12-10",
      },
      {
        id: "2",
        category: "DesignJobs",
        logo: "/company-2.png",
        title: "Graphic Designer",
        path: "",
        company: "ArtisticDesigns",
        location: "San Francisco",
        salary: "$190k -  $240k",
        datePosted: "2023-12-26",
      },
      {
        id: "3",
        category: "DesignJobs",
        logo: "/company-3.png",
        title: "Product Designer",
        path: "",
        company: "DesignHub",
        location: "Los Angeles",
        salary: "$160k -  $210k",
        datePosted: "2023-12-21",
      },
      {
        id: "4",
        category: "DesignJobs",
        logo: "/company-4.png",
        title: "Motion Graphics Specialist",
        path: "",
        company: "MotionMasters",
        location: "San Francisco",
        salary: "$200k -  $250k",
        datePosted: "2023-12-27",
      },
      {
        id: "5",
        category: "DesignJobs",
        logo: "/company-5.png",
        title: "UX/UI Lead",
        path: "",
        company: "DesignLeaders",
        location: "Seattle",
        salary: "$220k -  $280k",
        datePosted: "2023-12-28",
      },
      {
        id: "6",
        category: "DesignJobs",
        logo: "/company-6.png",
        title: "Web Designer",
        path: "",
        company: "WebCraft",
        location: "Denver",
        salary: "$170k -  $220k",
        datePosted: "2023-12-29",
      },
    ],
  },
];
